var SUBS = {
  stations: [
    {
      0: "",
      1: "<p>First steps</p>",
      4: "<p>From the so-called “Procuraduria de las misiones”</p>",
      8: "<p>built in 1730 with the blueprints attributed <br>to the Jesuit Father architect Juan Bautista Primoli,</p>",
      14: "<p>we enter the tunnels of <br>Manzana de las Luces.</p>",
      17: "<p>A modern construction serves as an entrance hall <br>to the tiny stairs that lead us there.</p>",
      23: "<p>Its existence in the Buenos Aires subsoil <br>fascinates whoever visits the site.</p>",
      29: "<p>Mysteries and enigmas surround <br>this colonial construction</p>",
      33: "<p>restored in the 1980s.</p>",
      37: "<p>Who built them? For what purpose? <br>Which series of events occurred in these galleries?</p>",
      44: "<p>Archaeology and history bring us <br>closer to some answers.</p>",
      50: "<p>We now know that these tunnels were built <br>by slaves and indigenous people</p>",
      54: "<p>under supervision of the Jesuit Fathers <br>between the 17th and 18th centuries.</p>",
      60: "<p>A fraction collapsed after the construction <br>of the Colegio Nacional de Buenos Aires,</p>",
      64: "<p>while the rest of the building still prevails under <br>the San Ignacio Church and</p>",
      69: "<p>the Complejo Histórico Cultural <br>Manzana de las Luces.</p>",
      71: "<p>We acknowledge that similar constructions <br>can be found in other latinamerican cities,</p>",
      77: "<p>where the Society of Jesus settled, <br>like Córdoba (Argentina) and Lima (Perú).</p>",
      83: "<p>Research shows the existence of <br>other types of tunnels</p>",
      87: "<p>under the Buenos Aires historic centre.</p>",
      90: "<p>Some are part of engineering constructions <br>to channel creeks</p>",
      94: "<p>like the Zanjón de Granados.</p>",
      96: "<p>Others are old cesspools <br>from the mid 19th century,</p>",
      102: "<p>and some are subsoil chambers <br>for electrical generators</p>",
      106: "<p>built right before the 20th century.</p>",
      109: "<p>During the visit we’ll cover the three sectors <br>that still prevail of these colonial tunnels</p>",
      115: "<p>Buenos Aires’ most ancient ones.</p>",
    },
    {
      0: "",
      1: "<p>The tunnels in the 19th century</p>",
      4: "<p>In 1848, as a consequence of <br>a police investigation</p>",
      8: "<p>related to an attack on <br>Juan Manuel de Rosas,</p>",
      12: "<p>newspapers mentioned the existence of <br>tunnels in the city’s subsoil.</p>",
      18: "<p>Among the older constructions, <br>Manzana de las Luces made its appearance.</p>",
      23: "<p>According to the press, the Jesuits obstructed <br>the tunnels when the Spanish king expelled them</p>",
      29: "<p>from their domain and they could have used <br>the passages to hide weapons</p>",
      33: "<p>and treasures during the British invasions.</p>",
      36: "<p>In 1893, almost fifty years later, <br>Federico Burmeister, son of the director of</p>",
      41: "<p>the Museum of Natural History, located <br>at the time in Manzana de las Luces,</p>",
      47: "<p>discovered a mysterious basement <br>that led to the deepness of olden times.</p>",
      53: "<p>Now we know it was just a cistern.</p>",
      57: "<p>During the same period of time, <br>other underground constructions appeared</p>",
      61: "<p>when old houses were demolished to <br>create a modern layout of Buenos Aires.</p>",
      66: "<p>The press echoed these fortuitous discoveries <br>and fed their readers</p>",
      72: "<p>with fantastic narrations that included <br>the findings of golden coins, human hair,</p>",
      77: "<p>ceramics and bones.</p>",
      80: "<p>Catacombs secretly built were also a subject of <br>discuss, as well as slave trade, complex sistems</p>",
      85: "<p>for defense, torture rooms and secret galeries <br>for romantic encounters.</p>",
      92: "<p>The stories suggested that the tunnels would <br>reach beyond the city limits</p>",
      96: "<p>and make it to Alta Gracia (Córdoba, Argentina) <br>and perhaps Alto Perú (Bolivia).</p>",
    },
    {
      0: "",
      1: "<p>First explorations</p>",
      3: "<p>Around 1912 a new sinking in Manzana <br>de las Luces uncovered a well.</p>",
      9: "<p>While building the foundations of <br>a drawing classroom,</p>",
      12: "<p>a part of the School of Architecture of <br>the University of Buenos Aires collapsed.</p>",
      17: "<p>Several students, Héctor Greslebin among them, <br>descended to the tunnels.</p>",
      23: "<p>Imagination sparkled on.</p>",
      26: "<p>Students of the Buenos Aires National School <br>narrated fantastic adventures</p>",
      29: "<p>and dreamt with passages conducting to <br>the Government House (Casa Rosada).</p>",
      33: "<p>In 1915, a request was made from the Ministry <br>of Public Works to the engineer E. Topelberg</p>",
      39: "<p>to develop a blueprint of the underground <br>galleries of Manzana de las Luces.</p>",
      44: "<p>As an architect with an interest in archeology, <br>Greslebin explored the galleries</p>",
      49: "<p>helped by the official plans. <br>In 1920 his results were published</p>",
      55: "<p>in a local newspaper and began <br>the first scientific study.</p>",
      60: "<p>Many years later he retakes those papers <br>in a conference published</p>",
      64: "<p>by the National Institute of Anthropology.</p>",
      68: "<p>Greslebin said:</p>",
      70: "<p>“I recognized under the so-called Manzana <br>de las Luces three main subterranean galleries</p>",
      74: "<p>and several subsidiaries. One runs from <br>south to north, it has an entrance on</p>",
      81: "<p>the National School, 15 meters from <br>Moreno St. and runs straight below Alsina St.</p>",
      88: "<p>The second tunnel comes from the southwest <br>and runs towards Perú St. Its north end</p>",
      94: "<p>disembogues on another tunnel. <br>This, the third one,</p>",
      100: "<p>starts at the edification line in Peru St. <br>by 30 meters from Alsina St.</p>",
      105: "<p>and runs straight towards the east <br>crossing the first described tunnel”.</p>",
    },
    {
      0: "",
      1: "<p>Recent times</p>",
      3: "<p>Above the tunnels that now can be visited, <br>the first National Council of Education</p>",
      8: "<p>was established. <br>Years later, the building of</p>",
      12: "<p>the Faculty of Exact, Físical and <br>Natural Science was constructed</p>",
      17: "<p>and also included Engineering and Architecture.</p>",
      20: "<p>In that place the “Noche de los Bastones Largos” <br>(The Night of the Long Batons) took place,</p>",
      27: "<p>on July 29th, 1966, when police forces of the <br>dictatorship invaded the cloisters</p>",
      31: "<p>and furiously beated students and professors.</p>",
      35: "<p>In 1971, the Faculty moved to the urban campus of <br>Buenos Aires University (Ciudad Universitaria)</p>",
      42: "<p>and began the demolition of the 20th century <br>buildings considered historically worthless.</p>",
      47: "<p>Manzana de las Luces lost one of its constructions. <br>Ten years later it was declared</p>",
      53: "<p>as a National Historic Monument <br>and its recovery was planned.</p>",
      58: "<p>As a part of the project, three sections <br>of the tunnels were recovered.</p>",
      62: "<p>The entrance was sketched over the <br>old Faculty of Engineering’s Aula Magna.</p>",
      66: "<p>At a crossing point between the tunnels <br>a vertical opening was made</p>",
      70: "<p>to the entrance stairs and ventilation.</p>",
      73: "<p>Galleries were expanded to facilitate the way, <br>tracks and an illumination system were installed.</p>",
      80: "<p>As a consequence, foundations of different <br>periods were uncovered.</p>",
      84: "<p>Those works didn´t have the participation <br>of professional archeologists.</p>",
      90: "<p>The Urban Archaeology studies <br>were developed years later</p>",
      95: "<p>after the last dictatorship.</p>",
      98: "<p>The study and scientific exploration <br>of the tunnels still is an outstanding debt.</p>",
    },
    {
      0: "",
      1: "<p>Afro-argentinians</p>",
      3: "<p>Since the 16th century millions were <br>kidnapped from their native Africa,</p>",
      9: "<p>enslaved and sold in America.</p>",
      12: "<p>These men and women, <br>as well as their descendants,</p>",
      15: "<p>worked servilely without giving up <br>the fight for freedom.</p>",
      19: "<p>Among them was María Remedios, <br>who was born in Buenos Aires in 1766.</p>",
      26: "<p>This woman, slaved by Doña Rosa del Valle, <br>had a recognized performance</p>",
      31: "<p>during the second english invasion <br>to the Rio de la Plata.</p>",
      35: "<p>Her assistance to the “Tercio de Andaluces” <br>was rewarded by the Cabildo de Buenos Aires.</p>",
      41: "<p>A few years later she joined the <br>revolutionaries of May</p>",
      45: "<p>and with her husband and sons <br>joined the Army of the North.</p>",
      49: "<p>During the Independence Wars, Remedios lost, <br>her entire family during the Battle of Ayohuma,</p>",
      53: "<p>in which she was captured and tortured <br>by the colonial armies.</p>",
      59: "<p>In recognition of her courage, <br>Belgrano named her captain</p>",
      63: "<p>while soldiers called her <br>“Mother of the Homeland”.</p>",
      68: "<p>As an elderly woman, she returned to Buenos Aires <br>where she found herself, as many others,</p>",
      73: "<p>reduced to mendicancy.</p>",
      76: "<p>It is said that she frequented the atrium of churches <br>selling “pasteles” and “torta fritas”</p>",
      81: "<p>In 1827, the Representative Board established in <br>Manzana de las Luces</p>",
      87: "<p>recognized Remedios’ patriotism and <br>made her captain of Infantry,</p>",
      91: "<p>paying a small pension.</p>",
      93: "<p>Years later, Juan Manuel de Rosas <br>promoted her to major sergeant of the Army</p>",
      98: "<p>and incremented her salary.</p>",
      100: "<p>This patriot passed away on November 8th, 1847. <br>In her honor, in our country, November 8th</p>",
      108: "<p>was established as National Day of Afro <br>Descendants and Afro Culture.</p>",
    },
    {
      0: "",
      1: "<p>Futuros posibles</p>",
      3: "<p>When democracy was restored in our country, <br>public access was inaugurated.</p>",
      7: "<p>For the first time it was possible to visit these <br>mystery surrounded constructions.</p>",
      11: "<p>As time went by, some preservation <br>tasks were made</p>",
      18: "<p>and the entrance to the tunnels was modified.</p>",
      22: "<p>The National Commission that administered <br>Manzana de las Luces since 1971, dissolved in</p>",
      27: "<p>2013 allowing the creation of the Historical <br>Cultural Complex of Manzana de las Luces,</p>",
      34: "<p>a new national museum.</p>",
      36: "<p>Many projects encourage cultural life in this <br>central place of Argentine history</p>",
      41: "<p>in which many important government <br>institutions have functioned</p>",
      44: "<p>since colonial times.</p>",
      47: "<p>In 2021, joined by the Museum <br>“José Antonio Terry” from Tilcara (Jujuy)</p>",
      53: "<p>and the Secretariat of Cultural Patrimony <br>of the Ministry of Culture,</p>",
      57: "<p>the project “An Argentine Tunnel” was initiated. <br>Under the proposal of</p>",
      61: "<p>“2084 Imagined Futures from the South”</p>",
      65: "<p>promoted by OLA (Observatory on Latin America) <br>of The New School, New York,</p>",
      71: "<p>we imagine a subterranean passage that <br>communicates the historical centre of Buenos Aires</p>",
      76: "<p>with the north of Argentina.</p>",
      78: "<p>Twelve youngsters are in this imagined place <br>to make the times to come.</p>",
    },
  ],
  estaciones: [
    {
      0: "",
      1: "<p>Primeros pasos</p>",
      4: "<p>Desde la llamada Procuraduría de las misiones,</p>",
      8: "<p>edificada de 1730 con planos atribuidos <br>al arquitecto jesuita Juan Bautista Prímoli,</p>",
      14: "<p>ingresamos a los túneles <br>de la Manzana de las Luces.</p>",
      17: "<p>Una moderna construcción sirve de antesala a la <br>pequeña escalera que nos conduce hacia ellos.</p>",
      23: "<p>Su existencia en el subsuelo de Buenos Aires <br>fascina a quienes los visitan.</p>",
      29: "<p>Misterios y dudas envuelven a estas <br> construcciones coloniales</p>",
      33: "<p>restauradas en la década de 1980.</p>",
      37: "<p>¿Quién los edificó? ¿Para qué se usaron? <br>¿Qué pasó en estas galerías?</p>",
      44: "<p>La arqueología y la historia <br>nos acercan algunas respuestas.</p>",
      50: "<p>Sabemos que a estos túneles los construyeron <br>esclavos e indígenas,</p>",
      54: "<p>bajo supervisión de los padres jesuitas, <br>entre los siglos XVII y XVIII.</p>",
      60: "<p>Una parte se derrumbó con la edificación <br>del Colegio Nacional Buenos Aires;</p>",
      64: "<p>otra aún pervive bajo la iglesia de San Ignacio y el <br>Complejo Histórico Cultural Manzana de las Luces.</p>",
      71: "<p>Sabemos que construcciones similares se <br>encuentran en otras ciudades latinoamericanas</p>",
      77: "<p>dónde se asentó la Compañía de Jesús <br>como Córdoba o Lima.</p>",
      83: "<p>Las investigaciones realizadas señalan la <br>existencia de otros tipos de túneles</p>",
      87: "<p>bajo el casco histórico de Buenos Aires.</p>",
      90: "<p>Algunos son parte de las obras de ingeniería <br>que encausaron pequeños arroyos</p>",
      94: "<p>como el Zanjón de Granados.</p>",
      96: "<p>Otros son antiguos pozos de basura <br>o cisternas de mediados del siglo XIX,</p>",
      102: "<p>otros son cámaras subterráneas <br>para generadores de electricidad</p>",
      106: "<p>construidas poco antes de empezar el siglo XX.</p>",
      109: "<p>Durante la visita recorreremos los tres sectores <br>que aún se conservan de estos túneles coloniales,</p>",
      115: "<p>los más antiguos de Buenos Aires.</p>",
    },
    {
      0: "",
      1: "<p>Los túneles en el siglo XIX</p>",
      4: "<p>En 1848, y como consecuencia <br>de una investigación policial</p>",
      8: "<p>relacionada con un atentado contra <br>la vida de Juan Manuel de Rosas,</p>",
      12: "<p>los periódicos mencionan la existencia <br>de diferentes túneles debajo de la ciudad.</p>",
      18: "<p>Entre las antiguas construcciones nombradas, <br>aparecen los de la Manzana de las Luces.</p>",
      23: "<p>De acuerdo con la prensa, los jesuitas los <br>obstruyeron cuando el rey español los expulsó</p>",
      29: "<p>de sus dominios y se habrían usado, para ocultar <br>armas y tesoros, durante las Invasiones inglesas.</p>",
      36: "<p>Casi cincuenta años después, en 1893, <br>Federico Burmeister, hijo del director</p>",
      41: "<p>del Museo de Historia Natural que funcionaba <br>en la Manzana de las Luces,</p>",
      47: "<p>descubrió un misterioso sótano <br>que conduciría a las profundidades del pasado.</p>",
      53: "<p>Ahora sabemos que era sólo una cisterna</p>",
      57: "<p>Por la misma época, aparecían otras <br>construcciones subterráneas</p>",
      61: "<p>cuando se demolían viejas casonas <br>y se trazaba una Buenos Aires moderna.</p>",
      66: "<p>La prensa se hacía eco de estos descubrimientos <br>fortuitos y alimentaba las fantasías de sus lectores</p>",
      72: "<p>con fantásticas narraciones que incluían el <br>hallazgo de monedas de oro, cabellos humanos,</p>",
      77: "<p>cerámicas y huesos.</p>",
      80: "<p>Se hablaba de catacumbas construidas en secreto, <br> tráfico de esclavos, complejos sistemas</p>",
      85: "<p>de defensa, salones de tortura, galerías secretas <br>para el encuentro de los amantes.</p>",
      92: "<p>Los túneles formarían una red <br>que iba más allá de la ciudad</p>",
      96: "<p>y llegaba hasta Alta Gracia y quizá al Alto Perú.</p>",
    },
    {
      0: "",
      1: "<p>Primeras exploraciones</p>",
      3: "<p>Hacia 1912, un nuevo hundimiento en la Manzana <br>de las Luces dejó al descubierto un pozo.</p>",
      9: "<p>Mientras se construían los cimientos <br>para una sala de dibujo,</p>",
      12: "<p>se derrumbó parte de la Escuela de Arquitectura <br>de la Universidad de Buenos Aires.</p>",
      17: "<p>Varios estudiantes, entre ellos Héctor Greslebin, <br>descendieron a los túneles.</p>",
      23: "<p>La imaginación volvió a encenderse.</p>",
      26: "<p>Estudiantes del Colegio Nacional <br>contaban fantásticas aventuras</p>",
      29: "<p>y soñaban con pasajes que los conducirían <br>a la Casa Rosada.</p>",
      33: "<p>En 1915, el Ministerio de Obras Pública <br>encargó al ingeniero E. Topelberg</p>",
      39: "<p>el trazado de un plano de las galerías <br>subterráneas de la Manzana de las Luces.</p>",
      44: "<p>Ya arquitecto e interesado en la arqueología, <br>Greslebin explora las galerías</p>",
      49: "<p>con la ayuda de los planos oficiales. <br>En 1920, publica sus hallazgos</p>",
      55: "<p>en un diario porteño e inicia los primeros <br>análisis científicos de los túneles.</p>",
      60: "<p>Muchos años después, retoma esos trabajos <br>en una conferencia publicada</p>",
      64: "<p>por el Instituto Nacional de Antropología</p>",
      68: "<p>Decía Greslebin:</p>",
      70: "<p>“Reconocí debajo de la llamada Manzana <br>de las Luces tres subterráneos principales</p>",
      74: "<p>y varios accesorios. Uno corre de sur a norte <br>tiene entrada por el Colegio Nacional</p>",
      81: "<p>a 15 metros de la calle Moreno y se dirige en línea <br>recta  hasta debajo de la calle Alsina.</p>",
      88: "<p>El segundo túnel, viene del sudoeste y corre en <br>dirección de calle Perú. Su extremo norte</p>",
      94: "<p>desemboca en otro túnel. Éste, el tercero, <br>se inicia a la altura de la perpendicular</p>",
      100: "<p>de la línea de edificación  de calle Perú, a unos 30 metros de calle Alsina,</p>",
      105: "<p>avanza de manera recta hacia el este <br>atravesando el primero de los túneles descritos”.</p>",
    },
    {
      0: "",
      1: "<p>Tiempos recientes</p>",
      3: "<p>Sobre parte de los túneles que actualmente <br>pueden visitarse funcionó la primera sede</p>",
      7: "<p>del Consejo Nacional de Educación. <br>Años después se construyó el edificio</p>",
      12: "<p>de la Facultad de Ciencias Exactas, <br>Físicas y Naturales que incluía también</p>",
      17: "<p>a Ingeniería y Arquitectura.</p>",
      20: "<p>En este lugar se vivió la Noche de los Bastones <br>Largos cuando el 29 de julio de 1966</p>",
      27: "<p>las fuerzas policiales de la dictadura <br>invadieron los claustros y golpearon</p>",
      31: "<p>furiosamente a estudiantes y docentes.</p>",
      35: "<p>En 1971, la Facultad completó su trasladó <br>a Ciudad Universitaria y comenzó la demolición</p>",
      42: "<p>de los edificios construidos en el siglo XX <br>considerados sin valor histórico.</p>",
      47: "<p>La Manzana de las Luces perdió una de sus partes. <br>Diez años después, el conjunto fue declarado</p>",
      53: "<p>Monumento Histórico Nacional <br>y se planificó su puesta en valor.</p>",
      58: "<p>Como parte del proyecto, <br>se restauraron tres sectores de los túneles.</p>",
      62: "<p>El ingreso se trazó sobre la antigua <br>Aula Magna de Ingeniería.</p>",
      66: "<p>En un punto de cruce, se realizó un hueco vertical <br>para colocar una escalera de ingreso y ventilación.</p>",
      73: "<p>También se ampliaron las galerías <br>para facilitar el paso, se colocaron caminos</p>",
      78: "<p>y un sistema de iluminación.</p>",
      80: "<p>Los trabajos dejaron al descubierto <br>cimientos de distintas épocas.</p>",
      84: "<p>Durante esos trabajos no se contó <br>con la participación</p>",
      87: "<p>de arqueólogos y arqueólogas profesionales.</p>",
      90: "<p>Los estudios de Arqueología Urbana <br>se desarrollaron algunos años después,</p>",
      95: "<p>pasada la última dictadura.</p>",
      98: "<p>Es una deuda pendiente el estudio <br>y exploración científica de los túneles.</p>",
    },
    {
      0: "",
      1: "<p>Afroargentinxs</p>",
      3: "<p>Desde el siglo XVI, millones de personas fueron <br>secuestradas en su África natal,</p>",
      9: "<p>esclavizadas y vendidas en América.</p>",
      12: "<p>Estos hombres y mujeres, <br>junto con sus descendientes,</p>",
      15: "<p>trabajaron en condiciones serviles <br>sin dejar de luchar por la libertad.</p>",
      19: "<p>Entre ellos estaba María Remedios <br>quien nació en Buenos Aires en 1766.</p>",
      26: "<p>Esta mujer, esclava de Doña Rosa del Valle, <br>tuvo una reconocida actuación</p>",
      31: "<p>durante la segunda invasión inglesa <br>al Rio de la Plata.</p>",
      35: "<p>Auxilió al Tercio de Andaluces y por ello obtuvo <br>una recompensa del Cabildo de Buenos Aires.</p>",
      41: "<p>Pocos años después, se sumó a los <br>revolucionarios de Mayo y se unió,</p>",
      45: "<p>con su marido e hijos, al Ejército del Norte.</p>",
      49: "<p>En las Guerras de la Independencia, <br>Remedios perdió a toda su familia</p>",
      53: "<p>y durante la batalla de Ayohuma, fue apresada <br>y torturada por los ejércitos coloniales.</p>",
      59: "<p>En reconocimiento de su valentía, <br>Belgrano la nombró capitana</p>",
      63: "<p>mientras que los soldados la llamaban <br>“madre de la Patria”.</p>",
      68: "<p>Ya anciana, regresó a Buenos Aires <br>donde se encontró, como tantos otros,</p>",
      73: "<p>reducida a la mendicidad.</p>",
      76: "<p>Se cuenta que frecuentaba el atrio de las iglesias <br>ofreciendo pasteles y tortas fritas.</p>",
      81: "<p>En 1827, la Junta de Representantes <br>que funcionaba en la Manzana de las Luces,</p>",
      87: "<p>reconoció el patriotismo de Remedios <br>y la nombró capitán de infantería</p>",
      91: "<p>con una pequeña pensión.</p>",
      93: "<p>Años después, Juan Manuel de Rosas <br>la ascendió a sargento mayor del ejército</p>",
      98: "<p>y aumentó su salario.</p>",
      100: "<p>Esta patriota falleció el 8 de noviembre de 1847. <br>En su honor, en nuestro país, se estableció</p>",
      108: "<p>al 8 de noviembre como el “Día Nacional <br>de los Afrodescendientes  y de la cultura afro”</p>",
    },
    {
      0: "",
      1: "<p>Futuros posibles</p>",
      3: "<p>Ya en democracia, se inauguró el acceso <br>del público a los túneles.</p>",
      7: "<p>Por primera vez se pudo visitar <br>estas construcciones</p>",
      11: "<p>que nunca dejaron de estar <br>rodeadas de misterios.</p>",
      14: "<p>Tiempo después se realizaron <br>algunas tareas de conservación</p>",
      18: "<p>y se modificó el ingreso a los túneles.</p>",
      22: "<p>La Comisión Nacional que administró <br>la Manzana de las Luces desde 1971</p>",
      27: "<p>se disolvió en 2013 dando lugar a la creación del <br>Complejo Histórico Cultural Manzana de las Luces;</p>",
      34: "<p>un nuevo museo nacional.</p>",
      36: "<p>Diversos proyectos alentaron la vida cultural <br>en este espacio central en la historia argentina</p>",
      41: "<p>por donde pasaron las más importantes <br>instituciones de gobierno</p>",
      44: "<p>desde los tiempos coloniales.</p>",
      47: "<p>En 2021, se inició junto con el Museo <br>“José Antonio Terry” de Tilcara</p>",
      53: "<p>y la Secretaría de Patrimonio Cultural <br>del Ministerio de Cultura</p>",
      57: "<p>el proyecto “Un túnel argentino” <br>en el marco de la propuesta</p>",
      61: "<p>“2084 Futuros Imaginados desde el Sur”</p>",
      65: "<p>promovida por OLA (Observatory on Latin <br>America) de la The New School, Nueva York,</p>",
      71: "<p>imaginamos un pasadizo subterráneo que <br>comunica el centro histórico de Buenos Aires</p>",
      76: "<p>y el norte argentino.</p>",
      78: "<p>En este espacio imaginado se encuentran <br>12 jóvenes para hacer un tiempo por venir.</p>",
    },
  ],
};
